In [60]:
import os
import zipfile
import pandas as pd

os.chdir('../2. Prepared Data')

ES_statistic_df = pd.read_csv('AirBase_ES_v8_statistics.zip', sep='\t', compression='zip')
FR_statistic_df = pd.read_csv('AirBase_FR_v8_statistics.zip', sep='\t', compression='zip')
PT_statistic_df = pd.read_csv('AirBase_PT_v8_statistics.zip', sep='\t', compression='zip')

statistic_df_raw = pd.concat([ES_statistic_df, FR_statistic_df, PT_statistic_df]) #fusion des df

statistic_df = statistic_df_raw[statistic_df_raw.statistic_name == 'annual mean'] #filtre sur la moyenne annuelle
statistic_df = statistic_df.iloc[:, [0,1,2,3,4,7,8,11]] #selection des colonnes utiles

statistic_df.to_csv("statistic_df.csv")

,station_european_code,component_code,component_name,component_caption,measurement_unit,statistics_year,statistics_average_group,statistic_value
1,ES0001R,1,Sulphur dioxide (air),SO2,µg/m3,1999,day,1.151
8,ES0001R,1,Sulphur dioxide (air),SO2,µg/m3,2008,day,0.384
15,ES0001R,1,Sulphur dioxide (air),SO2,µg/m3,2008,hour,0.393
23,ES0001R,1,Sulphur dioxide (air),SO2,µg/m3,1999,day,1.232
30,ES0001R,1,Sulphur dioxide (air),SO2,µg/m3,1999,hour,1.223
...,...,...,...,...,...,...,...,...
61225,PT02018,38,Nitrogen monoxide (air),NO,µg/m3,2009,hour,0.627
61230,PT02018,38,Nitrogen monoxide (air),NO,µg/m3,2011,day,0.577
61235,PT02018,38,Nitrogen monoxide (air),NO,µg/m3,2011,hour,0.584
61240,PT02018,38,Nitrogen monoxide (air),NO,µg/m3,2012,day,0.553
61245,PT02018,38,Nitrogen monoxide (air),NO,µg/m3,2012,hour,0.554

,station_european_code,component_code,component_name,component_caption,measurement_unit,measurement_european_group_code,statistics_period,statistics_year,statistics_average_group,statistic_shortname,statistic_name,statistic_value,statistics_percentage_valid,statistics_number_valid,statistics_calculated
0,ES0001R,1,Sulphur dioxide (air),SO2,µg/m3,100,Calendar year,1999,day,P50,50 percentile,0.000,63.562,232,Y
1,ES0001R,1,Sulphur dioxide (air),SO2,µg/m3,100,Calendar year,1999,day,Mean,annual mean,1.151,63.562,232,Y
2,ES0001R,1,Sulphur dioxide (air),SO2,µg/m3,100,Calendar year,1999,day,P95,95 percentile,7.500,63.562,232,Y
3,ES0001R,1,Sulphur dioxide (air),SO2,µg/m3,100,Calendar year,1999,day,P98,98 percentile,10.100,63.562,232,Y
4,ES0001R,1,Sulphur dioxide (air),SO2,µg/m3,100,Calendar year,1999,day,Max,maximum,25.100,63.562,232,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61244,PT02018,38,Nitrogen monoxide (air),NO,µg/m3,100,Calendar year,2012,hour,P50,50 percentile,0.000,97.621,8575,Y
61245,PT02018,38,Nitrogen monoxide (air),NO,µg/m3,100,Calendar year,2012,hour,Mean,annual mean,0.554,97.621,8575,Y
61246,PT02018,38,Nitrogen monoxide (air),NO,µg/m3,100,Calendar year,2012,hour,P95,95 percentile,3.000,97.621,8575,Y
61247,PT02018,38,Nitrogen monoxide (air),NO,µg/m3,100,Calendar year,2012,hour,P98,98 percentile,7.000,97.621,8575,Y
61248,PT02018,38,Nitrogen monoxide (air),NO,µg/m3,100,Calendar year,2012,hour,Max,maximum,32.000,97.621,8575,Y